version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    working_directory: /go/src/github.com/jtaylorcpp/gerl
    steps:
    - checkout
    - run: go get -v -t -d ./...
    - run: go test -v ./genserver ./process -coverprofile=circleci.cover
    - run: go tool cover -html=circleci.cover -o circleci.html
    - store_artifacts:
        path: ./circleci.html

