version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.13
    working_directory: /go/src/github.com/jtaylorcpp/gerl
    steps:
    - checkout
    - run: go get ./...
    - run: go test -v ./genserver ./process ./core -coverprofile=circleci.cover -bench=.
    - run: go tool cover -html=circleci.cover -o circleci.html
    - store_artifacts:
        path: ./circleci.html

