version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/jtaylorcpp/gerl
    steps:
    - checkout
    - run: go get -v -t -d ./...
    - run: go test -v ./... -coverprofile=circleci.cover
    - run: go cover tool -html=circleci.cover -o circleci.html

