// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GerlMsg_Type int32

const (
	GerlMsg_CALL GerlMsg_Type = 0
	GerlMsg_CAST GerlMsg_Type = 1
	GerlMsg_PROC GerlMsg_Type = 2
)

var GerlMsg_Type_name = map[int32]string{
	0: "CALL",
	1: "CAST",
	2: "PROC",
}

var GerlMsg_Type_value = map[string]int32{
	"CALL": 0,
	"CAST": 1,
	"PROC": 2,
}

func (x GerlMsg_Type) String() string {
	return proto.EnumName(GerlMsg_Type_name, int32(x))
}

func (GerlMsg_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1, 0}
}

type Message_Type int32

const (
	Message_SIMPLE   Message_Type = 0
	Message_SYNC     Message_Type = 1
	Message_REGISTER Message_Type = 2
)

var Message_Type_name = map[int32]string{
	0: "SIMPLE",
	1: "SYNC",
	2: "REGISTER",
}

var Message_Type_value = map[string]int32{
	"SIMPLE":   0,
	"SYNC":     1,
	"REGISTER": 2,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2, 0}
}

type Message_SubType int32

const (
	Message_GET     Message_SubType = 0
	Message_SET     Message_SubType = 1
	Message_PUT     Message_SubType = 2
	Message_DELETE  Message_SubType = 3
	Message_JOIN    Message_SubType = 4
	Message_REFRESH Message_SubType = 5
)

var Message_SubType_name = map[int32]string{
	0: "GET",
	1: "SET",
	2: "PUT",
	3: "DELETE",
	4: "JOIN",
	5: "REFRESH",
}

var Message_SubType_value = map[string]int32{
	"GET":     0,
	"SET":     1,
	"PUT":     2,
	"DELETE":  3,
	"JOIN":    4,
	"REFRESH": 5,
}

func (x Message_SubType) String() string {
	return proto.EnumName(Message_SubType_name, int32(x))
}

func (Message_SubType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2, 1}
}

type Health_Status int32

const (
	Health_ALIVE Health_Status = 0
)

var Health_Status_name = map[int32]string{
	0: "ALIVE",
}

var Health_Status_value = map[string]int32{
	"ALIVE": 0,
}

func (x Health_Status) String() string {
	return proto.EnumName(Health_Status_name, int32(x))
}

func (Health_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GerlMsg struct {
	Type                 GerlMsg_Type `protobuf:"varint,1,opt,name=type,proto3,enum=core.GerlMsg_Type" json:"type,omitempty"`
	Fromaddr             string       `protobuf:"bytes,2,opt,name=fromaddr,proto3" json:"fromaddr,omitempty"`
	Msg                  *Message     `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GerlMsg) Reset()         { *m = GerlMsg{} }
func (m *GerlMsg) String() string { return proto.CompactTextString(m) }
func (*GerlMsg) ProtoMessage()    {}
func (*GerlMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *GerlMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GerlMsg.Unmarshal(m, b)
}
func (m *GerlMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GerlMsg.Marshal(b, m, deterministic)
}
func (m *GerlMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GerlMsg.Merge(m, src)
}
func (m *GerlMsg) XXX_Size() int {
	return xxx_messageInfo_GerlMsg.Size(m)
}
func (m *GerlMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GerlMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GerlMsg proto.InternalMessageInfo

func (m *GerlMsg) GetType() GerlMsg_Type {
	if m != nil {
		return m.Type
	}
	return GerlMsg_CALL
}

func (m *GerlMsg) GetFromaddr() string {
	if m != nil {
		return m.Fromaddr
	}
	return ""
}

func (m *GerlMsg) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Message struct {
	Type                 Message_Type    `protobuf:"varint,1,opt,name=type,proto3,enum=core.Message_Type" json:"type,omitempty"`
	Subtype              Message_SubType `protobuf:"varint,2,opt,name=subtype,proto3,enum=core.Message_SubType" json:"subtype,omitempty"`
	Description          string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Values               []string        `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_SIMPLE
}

func (m *Message) GetSubtype() Message_SubType {
	if m != nil {
		return m.Subtype
	}
	return Message_GET
}

func (m *Message) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Message) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Health struct {
	Status               Health_Status `protobuf:"varint,1,opt,name=status,proto3,enum=core.Health_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Health) Reset()         { *m = Health{} }
func (m *Health) String() string { return proto.CompactTextString(m) }
func (*Health) ProtoMessage()    {}
func (*Health) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *Health) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Health.Unmarshal(m, b)
}
func (m *Health) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Health.Marshal(b, m, deterministic)
}
func (m *Health) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Health.Merge(m, src)
}
func (m *Health) XXX_Size() int {
	return xxx_messageInfo_Health.Size(m)
}
func (m *Health) XXX_DiscardUnknown() {
	xxx_messageInfo_Health.DiscardUnknown(m)
}

var xxx_messageInfo_Health proto.InternalMessageInfo

func (m *Health) GetStatus() Health_Status {
	if m != nil {
		return m.Status
	}
	return Health_ALIVE
}

func init() {
	proto.RegisterEnum("core.GerlMsg_Type", GerlMsg_Type_name, GerlMsg_Type_value)
	proto.RegisterEnum("core.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterEnum("core.Message_SubType", Message_SubType_name, Message_SubType_value)
	proto.RegisterEnum("core.Health_Status", Health_Status_name, Health_Status_value)
	proto.RegisterType((*Empty)(nil), "core.Empty")
	proto.RegisterType((*GerlMsg)(nil), "core.GerlMsg")
	proto.RegisterType((*Message)(nil), "core.Message")
	proto.RegisterType((*Health)(nil), "core.Health")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x6d, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0xf3, 0xd4, 0xa4, 0x9d, 0xf6, 0x64, 0x99, 0x43, 0x29, 0x7d, 0x63, 0x58, 0x0f, 0x29,
	0x0a, 0x11, 0xea, 0x27, 0x38, 0xea, 0xda, 0xeb, 0x99, 0x5e, 0xcb, 0x26, 0x27, 0xf8, 0x32, 0x6d,
	0xd7, 0x5a, 0x48, 0x4d, 0xc8, 0xa6, 0x42, 0x5f, 0xfa, 0x11, 0x04, 0x3f, 0xb0, 0xec, 0x83, 0xd2,
	0xca, 0xbd, 0x9b, 0x99, 0xff, 0x2f, 0x93, 0xf9, 0xcf, 0x0e, 0xc0, 0xae, 0xa9, 0x37, 0x49, 0xdd,
	0x54, 0x6d, 0x85, 0xc1, 0xa6, 0x6a, 0x04, 0x8d, 0xa0, 0xc3, 0x0e, 0x75, 0x7b, 0xa2, 0xbf, 0x5d,
	0x88, 0x66, 0xa2, 0x29, 0x17, 0x72, 0x87, 0xaf, 0x21, 0x68, 0x4f, 0xb5, 0x18, 0xba, 0xb1, 0x3b,
	0x7e, 0x36, 0xc1, 0x44, 0x91, 0x89, 0x15, 0x93, 0xfc, 0x54, 0x0b, 0xae, 0x75, 0x1c, 0x41, 0xf7,
	0x6b, 0x53, 0x1d, 0x8a, 0xed, 0xb6, 0x19, 0x7a, 0xb1, 0x3b, 0xee, 0xf1, 0x7f, 0x39, 0xbe, 0x04,
	0xff, 0x20, 0x77, 0x43, 0x3f, 0x76, 0xc7, 0xfd, 0xc9, 0x95, 0x69, 0xb1, 0x10, 0x52, 0x16, 0x3b,
	0xc1, 0x95, 0x42, 0x6f, 0x20, 0x50, 0xad, 0xb0, 0x0b, 0xc1, 0xf4, 0x36, 0x4d, 0x89, 0x63, 0xa2,
	0x2c, 0x27, 0xae, 0x8a, 0x56, 0x7c, 0x39, 0x25, 0x1e, 0xfd, 0xe5, 0x41, 0x64, 0x3f, 0x7b, 0x7a,
	0x2c, 0x2b, 0x9e, 0x8f, 0xf5, 0x0e, 0x22, 0x79, 0x5c, 0x6b, 0xd4, 0xd3, 0xe8, 0xf3, 0x4b, 0x34,
	0x3b, 0xae, 0x35, 0xfd, 0x97, 0xc2, 0x18, 0xfa, 0x5b, 0x21, 0x37, 0xcd, 0xbe, 0x6e, 0xf7, 0xd5,
	0x77, 0x3d, 0x73, 0x8f, 0x9f, 0x97, 0xf0, 0x05, 0x84, 0x3f, 0x8a, 0xf2, 0x28, 0xe4, 0x30, 0x88,
	0xfd, 0x71, 0x8f, 0xdb, 0x8c, 0xbe, 0xb1, 0x26, 0x00, 0xc2, 0x6c, 0xbe, 0x58, 0xa5, 0xcc, 0xd8,
	0xc8, 0xbe, 0x3c, 0x4c, 0x89, 0x8b, 0x03, 0xe8, 0x72, 0x36, 0x9b, 0x67, 0x39, 0xe3, 0xc4, 0xa3,
	0x33, 0x88, 0xec, 0x9f, 0x31, 0x02, 0x7f, 0xc6, 0x72, 0xe2, 0xa8, 0x20, 0x63, 0xca, 0x71, 0x04,
	0xfe, 0xea, 0x31, 0x27, 0x9e, 0xea, 0xf4, 0x81, 0xa5, 0x2c, 0x67, 0xc4, 0x57, 0x9d, 0xee, 0x97,
	0xf3, 0x07, 0x12, 0x60, 0x1f, 0x22, 0xce, 0x3e, 0x72, 0x96, 0xdd, 0x91, 0x0e, 0xbd, 0x87, 0xf0,
	0x4e, 0x14, 0x65, 0xfb, 0x0d, 0xdf, 0x42, 0x28, 0xdb, 0xa2, 0x3d, 0x4a, 0xbb, 0x93, 0x6b, 0x63,
	0xd4, 0xa8, 0x49, 0xa6, 0x25, 0x6e, 0x11, 0x7a, 0x0d, 0xa1, 0xa9, 0x60, 0x0f, 0x3a, 0xb7, 0xe9,
	0xfc, 0x33, 0x23, 0xce, 0xe4, 0xa7, 0x0b, 0x03, 0xfd, 0xb2, 0x66, 0x37, 0x8d, 0x5a, 0xf2, 0xb4,
	0x28, 0x4b, 0xbc, 0xba, 0x78, 0xf5, 0xd1, 0x65, 0x4a, 0x1d, 0xbc, 0x51, 0x9c, 0x6c, 0xff, 0xe7,
	0xfa, 0x26, 0x35, 0x37, 0xe5, 0xe0, 0x2b, 0x08, 0xf8, 0xe3, 0xf2, 0x13, 0x9e, 0x97, 0x47, 0x83,
	0xf3, 0x29, 0xa9, 0xb3, 0x0e, 0xf5, 0x41, 0xbe, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x30, 0x91,
	0xe4, 0x2e, 0x9e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GerlMessagerClient is the client API for GerlMessager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GerlMessagerClient interface {
	Call(ctx context.Context, in *GerlMsg, opts ...grpc.CallOption) (*GerlMsg, error)
	Cast(ctx context.Context, in *GerlMsg, opts ...grpc.CallOption) (*Empty, error)
	RUOK(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Health, error)
}

type gerlMessagerClient struct {
	cc *grpc.ClientConn
}

func NewGerlMessagerClient(cc *grpc.ClientConn) GerlMessagerClient {
	return &gerlMessagerClient{cc}
}

func (c *gerlMessagerClient) Call(ctx context.Context, in *GerlMsg, opts ...grpc.CallOption) (*GerlMsg, error) {
	out := new(GerlMsg)
	err := c.cc.Invoke(ctx, "/core.GerlMessager/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gerlMessagerClient) Cast(ctx context.Context, in *GerlMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/core.GerlMessager/Cast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gerlMessagerClient) RUOK(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Health, error) {
	out := new(Health)
	err := c.cc.Invoke(ctx, "/core.GerlMessager/RUOK", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GerlMessagerServer is the server API for GerlMessager service.
type GerlMessagerServer interface {
	Call(context.Context, *GerlMsg) (*GerlMsg, error)
	Cast(context.Context, *GerlMsg) (*Empty, error)
	RUOK(context.Context, *Empty) (*Health, error)
}

func RegisterGerlMessagerServer(s *grpc.Server, srv GerlMessagerServer) {
	s.RegisterService(&_GerlMessager_serviceDesc, srv)
}

func _GerlMessager_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GerlMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerlMessagerServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.GerlMessager/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerlMessagerServer).Call(ctx, req.(*GerlMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _GerlMessager_Cast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GerlMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerlMessagerServer).Cast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.GerlMessager/Cast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerlMessagerServer).Cast(ctx, req.(*GerlMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _GerlMessager_RUOK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerlMessagerServer).RUOK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.GerlMessager/RUOK",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerlMessagerServer).RUOK(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GerlMessager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.GerlMessager",
	HandlerType: (*GerlMessagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _GerlMessager_Call_Handler,
		},
		{
			MethodName: "Cast",
			Handler:    _GerlMessager_Cast_Handler,
		},
		{
			MethodName: "RUOK",
			Handler:    _GerlMessager_RUOK_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
